version: '3.7'

services:
  php-api:
    image: temabok-php-api-grep
    build:
      context: ./../
      dockerfile: devops/php-api-grep/Dockerfile
    container_name: temabok-php-api-grep
    networks:
      - wp_network

  nginx:
    image: temabok-nginx-grep
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: production
    container_name: temabok-nginx-grep
    depends_on:
      - php-api
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge