version: "3.7"

services:
  php-api:
    build:
      target: production
    entrypoint:
      [
        "/usr/local/bin/php_boot.sh",
      ]
    environment:
      - APP_DEBUG=true
      - APP_ENV=dev
      - APP_NAME=Temabok
      - APP_TIMEZONE=Europe/Kiev
      - APP_URL=https://app.skolerom-fw.com
      - AUTH_THIRD_PARTY_EMAIL=wp_computools_admin@gmail.com
      - AWS_BUCKET=dev-temabokwp
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - DATAPORTEN_POST_LOGOUT_REDIRECT_URI=https://app.skolerom-fw.com/login
      - DATAPORTEN_REDIRECT_URI=https://app.skolerom-fw.com/dataporten
      - DB_CONNECTION=mysql
      - DB_HOST=172.21.0.2
      - DB_PORT=3306
      - DB_DATABASE=wp-db3
      - DB_USERNAME=wp_user
      - DB_PASSWORD="XAma@jRS7ne&zG$$"
      - FILESYSTEM_DRIVER=public_uploads
      - LOG_CHANNEL=stack
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.eu.mailgun.org
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=null
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=12000
      - PHP_OPCACHE_MAX_WASTED_PERCENTAGE=10
      - PHP_OPCACHE_MEMORY_CONSUMPTION=192
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - QUEUE_CONNECTION=database
      - QUEUE_FAILED_DRIVER=database
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - SENTRY_LARAVEL_DSN=
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - TZ=Europe/Kiev
      - WP_URL=https://skolerom-test.com/
      - VIDEO_MANAGER_DOMAIN=https://app.skolerom-fw.com:8081:84
      - TEMABOK_EMAIL=alina.skorokhodova@computools.com
      - SSO_SKOLEROM_JWT_KEY=pP>8@6()sTvne,P7
      - SSO_SKOLEROM_SESSION_TIMEOUT_MINUTES=600
      - SSO_SKOLEROM_DOMAIN=app.skolerom-fw.com
      - SSO_COOKIE_NAME=sso-authcookie-skolerom
    
    volumes:
      - ./../../temabok-grep:/var/www/back
 
  nginx:
    # image: computoolsdevops/nginx:latest
    # container_name: temabok-nginx
    restart: always
    depends_on:
      - php-api
    environment:
      - TZ=Europe/Oslo
    ports:
      - 81:80

